# Generated by Django 4.0.3 on 2022-09-19 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem', models.FloatField(verbose_name='Atingido (%)')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.setores', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': '02 - Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='margens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem', models.FloatField(verbose_name='Atingido (%)')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.regras', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Margem',
                'verbose_name_plural': '01 - Margens',
            },
        ),
        migrations.CreateModel(
            name='gerentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=480, verbose_name='Centros de Custo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gestor')),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': '04 - Gerentes',
            },
        ),
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Funcionário')),
                ('codigo', models.CharField(max_length=64, verbose_name='Matrícula')),
                ('margem', models.FloatField(verbose_name='Atingido (%)')),
                ('salario', models.FloatField(verbose_name='Salário')),
                ('inicio', models.DateField(verbose_name='Inicio do Contrato')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim do Contato')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cargos', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': '03 - Funcionários',
            },
        ),
    ]
