# Generated by Django 4.0.3 on 2022-09-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filiais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Filial')),
                ('razao', models.CharField(max_length=128, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=128, verbose_name='CNPJ')),
                ('cidade', models.CharField(max_length=128, verbose_name='Cidade')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.CreateModel(
            name='formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo', models.IntegerField(verbose_name='Grupo ID')),
                ('matricula', models.CharField(max_length=32, verbose_name='Matrícula')),
                ('funcionario', models.CharField(max_length=128, verbose_name='Funcionário')),
                ('cargo', models.CharField(max_length=128, verbose_name='Cargo')),
                ('setor', models.CharField(max_length=128, verbose_name='Setor')),
                ('tipo', models.CharField(max_length=2, verbose_name='Receita/Despesa')),
                ('filial', models.CharField(max_length=128, verbose_name='Filial')),
                ('ll_peso', models.FloatField(verbose_name='Peso Lucro Líquido Global')),
                ('ll_meta', models.FloatField(verbose_name='Meta Lucro Líquido Global')),
                ('ll_atingido', models.FloatField(verbose_name='Resultado Lucro Líquido Global')),
                ('ll_margem', models.FloatField(verbose_name='Mergem Lucro Líquido Global')),
                ('ms_peso', models.FloatField(verbose_name='Peso Market Share')),
                ('ms_meta', models.FloatField(verbose_name='Meta Market Share')),
                ('ms_atingido', models.FloatField(verbose_name='Resultado Market Share')),
                ('ms_margem', models.FloatField(verbose_name='Margem Market Share')),
                ('ec_peso', models.FloatField(verbose_name='Peso Experiência do Cliente')),
                ('ec_meta', models.FloatField(verbose_name='Meta Experiência do Cliente')),
                ('ec_atingido', models.FloatField(verbose_name='Resultado Experiência do Cliente')),
                ('ec_margem', models.FloatField(verbose_name='Margem Experiência do Cliente')),
                ('dv_peso', models.FloatField(verbose_name='Peso Despesa Sobre Venda')),
                ('dv_meta', models.FloatField(verbose_name='Meta Despesa Sobre Venda')),
                ('dv_atingido', models.FloatField(verbose_name='Resultado Despesa Sobre Venda')),
                ('dv_margem', models.FloatField(verbose_name='Margem Despesa Sobre Venda')),
                ('oc_peso', models.FloatField(verbose_name='Peso Orçamento da Área')),
                ('oc_meta', models.FloatField(verbose_name='Meta Orçamento da Área')),
                ('oc_atingido', models.FloatField(verbose_name='Resultado Orçamento da Área')),
                ('oc_margem', models.FloatField(verbose_name='Margem Orçamento da Área')),
                ('ii_peso', models.FloatField(verbose_name='Peso Indicador Individual')),
                ('ii_meta', models.FloatField(verbose_name='Meta Indicador Individual')),
                ('ii_atingido', models.FloatField(verbose_name='Resultado Indicador Individual')),
                ('ii_margem', models.FloatField(verbose_name='Margem Indicador Individual')),
                ('salario', models.FloatField(verbose_name='Salário')),
                ('margem_total', models.FloatField(verbose_name='Total Margem')),
                ('nome_regua', models.CharField(max_length=32, verbose_name='Tipo Régua')),
                ('valor_regua', models.FloatField(verbose_name='Régua')),
                ('premio_total', models.FloatField(verbose_name='Total PPR')),
                ('status', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
            ],
            options={
                'verbose_name': 'Hitórico PPR',
                'verbose_name_plural': 'Hitórico PPR',
            },
        ),
        migrations.CreateModel(
            name='regras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regra', models.CharField(max_length=64, verbose_name='Regra')),
                ('peso', models.FloatField(verbose_name='Peso (%)')),
                ('meta', models.FloatField(verbose_name='Meta (%)')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
            ],
            options={
                'verbose_name': 'Peso e Meta',
                'verbose_name_plural': 'Pesos & Metas',
            },
        ),
        migrations.CreateModel(
            name='reguas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regua', models.CharField(max_length=64, verbose_name='Régua')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
            ],
            options={
                'verbose_name': 'Régua',
                'verbose_name_plural': 'Réguas',
            },
        ),
        migrations.CreateModel(
            name='setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=64, verbose_name='Setor')),
                ('tipo', models.CharField(choices=[('R', 'RECEITA'), ('D', 'DESPESA')], max_length=64, verbose_name='tipo')),
                ('centro_custo', models.CharField(max_length=64, verbose_name='Centro de Custo')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filiais', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.FloatField(verbose_name='Mínimo')),
                ('maximo', models.FloatField(verbose_name='Máximo')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('regua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reguas', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Nível da Régua',
                'verbose_name_plural': 'Níveis da Régua',
            },
        ),
        migrations.CreateModel(
            name='cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=64, verbose_name='Cargo')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('regua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reguas', verbose_name='Régua')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.setores', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
    ]
